org:
  quartz:
    scheduler:
      instanceName: DefaultQuartzScheduler
      instanceId: AUTO  #ID设置为自动获取 每一个必须不同
      makeSchedulerThreadDaemon: true
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      makeThreadsDaemons: true
      threadCount: 20
      threadPriority: 5
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      tablePrefix: QRTZ_
      isClustered: true
      misfireThreshold: 25000