server:
  port: 80

spring:
  application:
    name: pie-gateway-service
  cloud:
    gateway:
      #      globalcors:
      #        corsConfigurations:
      #          '[/**]':
      #            # 允许携带认证信息
      #            allow-credentials: true
      #            # 允许跨域的源(网站域名/ip)，设置*为全部
      #            allowedOriginPatterns: "*"
      #            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
      #            allowedMethods: "*"
      #            # 允许跨域请求里的head字段，设置*为全部
      #            allowedHeaders: "*"
      #        default-filters:
      #          - DedupeResponseHeader = Access-Control-Allow-Origin, RETAIN_UNIQUE
      discovery:
        locator:
          enabled: true #启用自动根据服务ID生成路由
          lower-case-service-id: true # 设置路由的路径为小写的服务ID

      routes:
        - id: pie-admin-service   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://pie-admin-service
          predicates:
            - Path=/pie-admin/** #断言，路由匹配进的进行路由
          filters:
            - StripPrefix=1 #移除前缀 pie-admin

        - id: pie-security-service   #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://pie-security-service
          predicates:
            - Path=/pie-security/** #断言，路由匹配进的进行路由
          filters:
            - StripPrefix=1 #移除前缀 pie-admin

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'